from .settings import (
    ROOT_DIR,
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    REFERENCE_DATA_DIR,
    DB_PATH,
    XPF_TO_EUR_RATE,
    DEFAULT_NOTARY_FEES_RATIO,
    TGC_IMMOBILIER_TAUX,
    DEFAULT_HEADERS,
)
