from datetime import datetime, timezone
from typing import List
from src.models.listing import RawListing


def get_pilot_dataset() -> List[RawListing]:
    """
    Génère un jeu d'annonces représentatives et fidèles à la réalité du marché
    du Grand Nouméa (Nouméa, Dumbéa, Mont-Dore, Païta).
    Permet des tests reproductibles, hors-ligne et immédiats du pipeline ETL.
    """
    items = [
        # --- NOUMEA SUD ---
        RawListing(
            source="immobilier.nc",
            source_id="10101",
            url="https://www.immobilier.nc/details/10101",
            title="Appartement F3 de standing avec magnifique vue mer Anse Vata",
            description="Superbe appartement F3 rénové avec goût dans résidence sécurisée avec ascenseur. Salon lumineux ouvrant sur terrasse couverte de 24 m², cuisine équipée américaine, 2 chambres climatisées avec placards, salle d'eau à l'italienne, volets roulants électriques. Cellier et 2 places de parking couvertes et sécurisées.",
            raw_price="48 500 000 F",
            raw_surface="82 m²",
            raw_rooms="F3",
            raw_location="Nouméa - Anse Vata",
            transaction_type_declared="Vente",
            property_type_declared="Appartement",
            agency_name="Agence du Lagon",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="bienmeloger.nc",
            source_id="20202",
            url="https://www.bienmeloger.nc/annonces/20202",
            title="Villa F5 contemporaine avec piscine et deck Val Plaisance",
            description="Rare à la vente au cœur de Val Plaisance, spacieuse villa familiale F5 d'architecte. Séjour avec belle hauteur sous plafond, varangue de 40m² face à la piscine maçonnée et jardin arboré sans vis-à-vis. 4 chambres climatisées dont suite parentale avec dressing, cuisine haut standing en kohu. Terrain plat clôturé de 7 ares 50. Carport 2 véhicules.",
            raw_price="89 MF",
            raw_surface="175 m²",
            raw_rooms="F5",
            raw_location="Nouméa Val Plaisance",
            transaction_type_declared="Vente",
            property_type_declared="Villa",
            agency_name="Prestige NC Immobilier",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="immobilier.nc",
            source_id="10103",
            url="https://www.immobilier.nc/details/10103",
            title="Studio meublé avec vue baie Baie des Citrons",
            description="Idéal investisseur ou pied-à-terre ! Studio de 32m² entièrement équipé et climatisé, terrasse de 8m² avec aperçu mer, résidence sécurisée avec digicode et piscine commune. Actuellement loué en bail meublé. Charges de copropriété modérées.",
            raw_price="18 900 000 XPF",
            raw_surface="32 m²",
            raw_rooms="F1",
            raw_location="Baie des Citrons",
            transaction_type_declared="Vente",
            property_type_declared="Studio",
            agency_name="Alizés Immo",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="immobilier.nc",
            source_id="10104",
            url="https://www.immobilier.nc/details/10104",
            title="À louer - Bel appartement F2 meublé Baie de Sainte-Marie Ouémo",
            description="Dans un cadre privilégié sur la presqu'île de Ouémo, F2 meublé climatisé comprenant séjour, varangue fermée, cuisine moderne, chambre avec dressing, salle d'eau. Place de parking sécurisée dans résidence calme.",
            raw_price="135 000 F/mois",
            raw_surface="48 m²",
            raw_rooms="F2",
            raw_location="Nouméa - Ouémo",
            transaction_type_declared="Location",
            property_type_declared="Appartement",
            agency_name="Top Immo",
            extracted_at=datetime.now(timezone.utc),
        ),

        # --- NOUMEA CENTRE & RESIDENTIEL ---
        RawListing(
            source="immobilier.nc",
            source_id="10105",
            url="https://www.immobilier.nc/details/10105",
            title="Maison coloniale de caractère Vallée des Colons VDC",
            description="Coup de cœur assuré ! Véritable maison de style colonial au Faubourg Blanchot / Vallée des Colons. 3 chambres spacieuses avec plancher d'origine, salon avec cheminée d'ornement, cuisine rénovée, grande véranda couverte de 35 m². Terrain arboré de 5 ares 20. Proche tous commerces et écoles.",
            raw_price="45.000.000 F",
            raw_surface="120 m²",
            raw_rooms="F4",
            raw_location="Vallée des Colons (VDC)",
            transaction_type_declared="Vente",
            property_type_declared="Maison",
            agency_name="Agence Générale",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="bienmeloger.nc",
            source_id="20206",
            url="https://www.bienmeloger.nc/annonces/20206",
            title="Location F3 spacieux proche aérodrome de Magenta",
            description="Grand F3 traversant au 2ème étage, salon donnant sur balcon, cuisine indépendante, 2 chambres avec placards, WC séparé. Climatisation, volets roulants, parking couvert. Quartier calme proche plage de Magenta.",
            raw_price="110 000 F",
            raw_surface="70 m²",
            raw_rooms="F3",
            raw_location="Nouméa - Magenta",
            transaction_type_declared="Location",
            property_type_declared="Appartement",
            agency_name="Sogeti NC",
            extracted_at=datetime.now(timezone.utc),
        ),

        # --- DUMBEA ---
        RawListing(
            source="immobilier.nc",
            source_id="10107",
            url="https://www.immobilier.nc/details/10107",
            title="Villa F4 récente avec jardin clôturé Dumbéa-sur-Mer DSM",
            description="Exclusivité : Proche du Médipôle et des écoles de Dumbéa sur mer, charmante villa F4 en construction maçonnée. Pièce de vie avec cuisine US aménagée, 3 chambres climatisées, terrasse couverte de 18 m², jardin plat piscinable de 4 ares 80. Lotissement résidentiel calme.",
            raw_price="28 500 000 F",
            raw_surface="95 m²",
            raw_rooms="F4",
            raw_location="Dumbéa sur mer",
            transaction_type_declared="Vente",
            property_type_declared="Villa",
            agency_name="Médipôle Immobilier",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="immobilier.nc",
            source_id="10108",
            url="https://www.immobilier.nc/details/10108",
            title="Appartement F2 Koutio proche lycée et collège",
            description="Idéal premier achat ou investissement locatif rentable. Appartement F2 au 1er étage avec terrasse de 10m², chambre climatisée avec salle d'eau attenante, séjour cuisine. Parking sécurisé.",
            raw_price="13 500 000 F",
            raw_surface="44 m²",
            raw_rooms="F2",
            raw_location="Koutio, Dumbéa",
            transaction_type_declared="Vente",
            property_type_declared="Appartement",
            agency_name="Top Immo",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="bienmeloger.nc",
            source_id="20209",
            url="https://www.bienmeloger.nc/annonces/20209",
            title="Location Villa F4 Koutio avec jardin privatif",
            description="Villa individuelle F4 comprenant séjour lumineux, cuisine semi-équipée, 3 chambres dont une parentale, terrasse, terrain clôturé. Proche zone commerciale Kenu-In Auteuil.",
            raw_price="130 000 F/mois",
            raw_surface="90 m²",
            raw_rooms="F4",
            raw_location="Auteuil Dumbéa",
            transaction_type_declared="Location",
            property_type_declared="Villa",
            agency_name="Agence du Sud",
            extracted_at=datetime.now(timezone.utc),
        ),

        # --- PAITA ---
        RawListing(
            source="immobilier.nc",
            source_id="10110",
            url="https://www.immobilier.nc/details/10110",
            title="Prestigieuse Villa F5 Savannah vue panoramique montagne et mer",
            description="Dans le lotissement sécurisé et prisé de Savannah, somptueuse villa F5 contemporaine de 210m² habitables. Immense séjour ouvrant sur deck en kohu de 80m² et piscine à débordement. Suite parentale d'exception avec dressing et salle de bains balnéo, 3 grandes chambres pour enfants, bureau, cellier, double garage fermé. Terrain paysagé de 22 ares entièrement sécurisé.",
            raw_price="78 000 000 F",
            raw_surface="210 m²",
            raw_rooms="F5",
            raw_location="Savannah, Païta",
            transaction_type_declared="Vente",
            property_type_declared="Villa",
            agency_name="Prestige NC",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="immobilier.nc",
            source_id="10111",
            url="https://www.immobilier.nc/details/10111",
            title="Villa F4 Beauvallon Païta plain-pied lotissement calme",
            description="Agréable villa F4 de 2018 avec séjour carrelé, cuisine équipée, varangue de 22 m², 3 chambres climatisées, salle d'eau avec douche à l'italienne. Terrain plat clôturé de 6 ares avec portail électrique.",
            raw_price="29 900 000 F",
            raw_surface="100 m²",
            raw_rooms="F4",
            raw_location="Beauvallon, Païta",
            transaction_type_declared="Vente",
            property_type_declared="Maison",
            agency_name="Nord Ouest Immo",
            extracted_at=datetime.now(timezone.utc),
        ),

        # --- MONT-DORE ---
        RawListing(
            source="bienmeloger.nc",
            source_id="20212",
            url="https://www.bienmeloger.nc/annonces/20212",
            title="Villa F4 Robinson Mont-Dore avec piscine et grand deck",
            description="Située dans un quartier calme et recherché de Robinson, villa F4 comprenant salon séjour climatisé, terrasse couverte avec vue dégagée, deck en bois entourant une belle piscine, 3 chambres, cuisine équipée. Terrain de 8 ares arboré.",
            raw_price="36 500 000 F",
            raw_surface="115 m²",
            raw_rooms="F4",
            raw_location="Robinson Mont-Dore",
            transaction_type_declared="Vente",
            property_type_declared="Villa",
            agency_name="Tropic Immo",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="immobilier.nc",
            source_id="10113",
            url="https://www.immobilier.nc/details/10113",
            title="Appartement F3 avec vue mer Boulari Marina",
            description="Appartement F3 spacieux face au port de Boulari. Séjour avec cuisine ouverte, terrasse de 15m² avec belle vue sur les bateaux et le lagon, 2 chambres climatisées, cellier et parking couvert sécurisé.",
            raw_price="24 000 000 F",
            raw_surface="68 m²",
            raw_rooms="F3",
            raw_location="Boulari, Mont-Dore",
            transaction_type_declared="Vente",
            property_type_declared="Appartement",
            agency_name="Agence du Sud",
            extracted_at=datetime.now(timezone.utc),
        ),
        RawListing(
            source="immobilier.nc",
            source_id="10114",
            url="https://www.immobilier.nc/details/10114",
            title="Location Villa F5 Vallon-Dore bord de mer",
            description="Superbe villa les pieds dans l'eau au Vallon-Dore. Grand séjour lumineux ouvrant sur vaste varangue, accès plage direct, 4 chambres, jardin arboré de 12 ares. Environnement très paisible.",
            raw_price="165 000 F/mois",
            raw_surface="150 m²",
            raw_rooms="F5",
            raw_location="Vallon Dore, Mont-Dore",
            transaction_type_declared="Location",
            property_type_declared="Villa",
            agency_name="Alizés Immo",
            extracted_at=datetime.now(timezone.utc),
        ),
    ]
    return items
